# Setup
title: TECHNOLOGY MATTERS
tagline: a bunch of unordered thoughts about tech, software, etc.
url: "https://blog.brunobrant.net" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 1
#baseurl: "https://blog.brunobrant.net"
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Bruno Brant
  url: https://twitter.com/heavystorm
  #email: heavy_storm@hotmail.com

social_links:
  github: bruno-brant
  twitter: HeavyStorm
  stackoverflow: "227332/bruno-brant"
  linkedin: brunobrant

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/bruno-brant/bruno-brant.github.io
